<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Homes extends \App\Entity\Homes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'service', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'rooms', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'surface', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'active', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'furnished', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'createdat', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'updatedat', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'pictures', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'userslikes', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'bedrooms', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'bathrooms', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'requests', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'viewcounter', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'googlemap', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'currentuser', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'viewStats'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'service', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'rooms', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'surface', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'active', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'furnished', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'createdat', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'updatedat', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'pictures', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'userslikes', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'bedrooms', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'bathrooms', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'requests', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'viewcounter', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'googlemap', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'currentuser', '' . "\0" . 'App\\Entity\\Homes' . "\0" . 'viewStats'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Homes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRequestUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestUsers', []);

        return parent::getRequestUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getService(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', []);

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function setService(string $service): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', [$service]);

        return parent::setService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getRooms(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRooms', []);

        return parent::getRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setRooms(int $rooms): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRooms', [$rooms]);

        return parent::setRooms($rooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurface(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurface', []);

        return parent::getSurface();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurface(int $surface): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurface', [$surface]);

        return parent::setSurface($surface);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(int $price): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress(string $adress): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictures(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictures', []);

        return parent::getPictures();
    }

    /**
     * {@inheritDoc}
     */
    public function setPictures(?array $pictures): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPictures', [$pictures]);

        return parent::setPictures($pictures);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(int $active): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getFurnished(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFurnished', []);

        return parent::getFurnished();
    }

    /**
     * {@inheritDoc}
     */
    public function setFurnished(bool $furnished): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFurnished', [$furnished]);

        return parent::setFurnished($furnished);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedat(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedat', []);

        return parent::getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedat(\DateTimeInterface $createdat): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedat', [$createdat]);

        return parent::setCreatedat($createdat);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedat(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedat', []);

        return parent::getUpdatedat();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedat(\DateTimeInterface $updatedat): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedat', [$updatedat]);

        return parent::setUpdatedat($updatedat);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserslikes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserslikes', []);

        return parent::getUserslikes();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserslike(\App\Entity\Users $userslike): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserslike', [$userslike]);

        return parent::addUserslike($userslike);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserslike(\App\Entity\Users $userslike): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserslike', [$userslike]);

        return parent::removeUserslike($userslike);
    }

    /**
     * {@inheritDoc}
     */
    public function getBedrooms(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBedrooms', []);

        return parent::getBedrooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setBedrooms(?int $bedrooms): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBedrooms', [$bedrooms]);

        return parent::setBedrooms($bedrooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getBathrooms(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBathrooms', []);

        return parent::getBathrooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setBathrooms(?int $bathrooms): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBathrooms', [$bathrooms]);

        return parent::setBathrooms($bathrooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequests(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequests', []);

        return parent::getRequests();
    }

    /**
     * {@inheritDoc}
     */
    public function addRequest(\App\Entity\Requests $request): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRequest', [$request]);

        return parent::addRequest($request);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRequest(\App\Entity\Requests $request): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRequest', [$request]);

        return parent::removeRequest($request);
    }

    /**
     * {@inheritDoc}
     */
    public function getViewcounter(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewcounter', []);

        return parent::getViewcounter();
    }

    /**
     * {@inheritDoc}
     */
    public function setViewcounter(int $viewcounter): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViewcounter', [$viewcounter]);

        return parent::setViewcounter($viewcounter);
    }

    /**
     * {@inheritDoc}
     */
    public function getGooglemap(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGooglemap', []);

        return parent::getGooglemap();
    }

    /**
     * {@inheritDoc}
     */
    public function setGooglemap(?string $googlemap): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGooglemap', [$googlemap]);

        return parent::setGooglemap($googlemap);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentuser(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentuser', []);

        return parent::getCurrentuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentuser(?\App\Entity\Users $currentuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentuser', [$currentuser]);

        return parent::setCurrentuser($currentuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getViewStats(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewStats', []);

        return parent::getViewStats();
    }

    /**
     * {@inheritDoc}
     */
    public function addViewStat(\App\Entity\ViewStats $viewStat): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addViewStat', [$viewStat]);

        return parent::addViewStat($viewStat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeViewStat(\App\Entity\ViewStats $viewStat): \App\Entity\Homes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeViewStat', [$viewStat]);

        return parent::removeViewStat($viewStat);
    }

}
