<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU9a2j4H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU9a2j4H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU9a2j4H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU9a2j4H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU9a2j4H\App_KernelDevDebugContainer([
    'container.build_hash' => 'U9a2j4H',
    'container.build_id' => '609dfaf1',
    'container.build_time' => 1582136531,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU9a2j4H');
